# Site settings
title: Testing Stuff
email: virtua.creative@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/test/" # the subpath of your site, e.g. /blog
url: "http://virtuacreative.github.io" # the base hostname & protocol for your site
twitter_username: virtuacreative
github_username:  virtuacreative
highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:title/
keep_files: [php]
